name: Extract and Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Extract ZIP
        run: |
          ZIP=$(find . -name "*.zip" | head -n 1)

          if [ -n "$ZIP" ]; then
            echo "ZIP found: $ZIP"
            mkdir extracted
            unzip -o "$ZIP" -d extracted
          else
            echo "No ZIP found"
          fi

      - name: Find Flutter Project
        id: project
        run: |
          PROJECT=$(find . -name pubspec.yaml | head -n 1 | xargs dirname)
          echo "Project=$PROJECT"
          echo "PROJECT_DIR=$PROJECT" >> $GITHUB_ENV

      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter Pub Get
        working-directory: ${{ env.PROJECT_DIR }}
        run: flutter pub get

      - name: Build APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: attendance-app-apk
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
